receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
      http:
        endpoint: 0.0.0.0:55681
  sapm:
    endpoint: 0.0.0.0:7276
  signalfx:
    endpoint: 0.0.0.0:9943
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch: null
  memory_limiter:
    ballast_size_mib: 683
    check_interval: 5s
    limit_mib: 400
    spike_limit_mib: 100
  queued_retry: null

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"

extensions:
  health_check:
    port: 13133

service:
  extensions:
  - health_check
  pipelines:
    # logs:
    #   exporters:
    #   - signalfx
    #   processors:
    #   - memory_limiter
    #   receivers:
    #   - signalfx
    # metrics:
    #   exporters:
    #   - signalfx
    #   processors:
    #   - memory_limiter
    #   receivers:
    #   - signalfx
    traces:
      exporters:
      - zipkin
      processors:
      - memory_limiter
      - queued_retry
      - batch
      receivers:
      - sapm
      - zipkin
      - jaeger
      - otlp
